name: new_flutter
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icons/translatoricon.webp"


flutter:
  uses-material-design: true
  assets:
    - lib/assets/body.json
    - lib/assets/languageslist.json
    - lib/assets/icons/

